[package]
name = "random-art"
version = "0.1.0"
authors = ["R4chel"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket="0.4.6"
rand = "0.6.1"